services:
  address-db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - address-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=address
    healthcheck:
      test: pg_isready -U postgres -d address -h localhost -p 5432
      interval: 10s
      timeout: 5s
      retries: 3
  address:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://address-db:5432/address
      - SPRING_FLYWAY_URL=jdbc:postgresql://address-db:5432/address
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRIC_EXPORT_INTERVAL=5000
      - OTEL_LOGS_EXPORTER=none
      - OTEL_INSTRUMENTATION_HTTP_CLIENT_EMIT_EXPERIMENTAL_TELEMETRY=true
      - OTEL_INSTRUMENTATION_HTTP_SERVER_EMIT_EXPERIMENTAL_TELEMETRY=true
      - OTEL_SERVICE_NAME=address
      - OTEL_TRACES_EXPORTER=none
    healthcheck:
      test: wget -qO - http://localhost:8080/health || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      address-db:
        condition: service_healthy
  address-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "address",
      "--app-port", "${EXPERIMENT_CONFIG_SIDECAR_PORT:-8080}",
      "--dapr-http-port", "3500",
      "-placement-host-address", "placement:50006",
      "--config", "/config.yaml",
      "--resources-path", "/components"
    ]
    network_mode: "service:address"
volumes:
  address-db-data:
